#!/bin/bash
echo ${VIRTUAL_ENV}
export PATH=/root/maintainer-quality-tools/travis:/root/venv/bin:${PATH}
echo ${PATH}
export TESTS=1 ODOO_REPO="OCA/OCB"
/root/venv/bin/python /root/maintainer-quality-tools/travis/travis_run_tests
